version: '3'

include:
  - ./spark-cluster/docker-compose.yaml

networks:
  log_searchq_network:
    driver: bridge

services:
  keycloak-server:
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import/
    command: start-dev --import-realm
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8082:8080"
    depends_on:
      - postgresql-server
    networks:
      - log_searchq_network

  frontend-app:
    build: ./frontend-app
    image: consorziorfx/frontend-app:1.0
    restart: unless-stopped
    environment:
      - REACT_APP_KEYCLOAK_ENDPOINT=http://localhost:8082
      - REACT_APP_LOGBOOK_BACKEND_ENDPOINT=http://localhost:8081
      - REACT_APP_QUERY_ENGINE_ENDPOINT=http://localhost:5001
    ports:
      - "3000:3000"
    networks:
      - log_searchq_network

  logbook-backend:
    build: ./logbook-backend
    image: consorziorfx/logbook-backend:1.0
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://helloworld:helloworld@postgresql-server:5432/logbookdb
      - KEYCLOAK_URL=http://keycloak-server:8080
    ports:
      - "8081:8081"
    depends_on:
      - postgresql-server
    networks:
      - log_searchq_network

  query-engine:
    build: ./query-engine
    image: consorziorfx/query-engine:1.0
    restart: unless-stopped
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - DATABASE_URL=postgresql://helloworld:helloworld@postgresql-server:5432/logbookdb
    ports:
      - "5001:5001"
      - "4042:4042"
    depends_on:
      - postgresql-server
      - spark-master
    networks:
      - log_searchq_network

  # nginx:
  #   image: nginx:latest
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - frontend
  #     - logbook-backend
  #     - keycloak
  #   networks:
  #     - log-searchq_network:

  # postgresql-server:
  #   image: postgres
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=helloworld
  #     - POSTGRES_PASSWORD=helloworld
  #     - POSTGRES_DB=logbookdb
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - ./data:/var/lib/postgresql/data
  #     - ./logbookRFX.sql:/logbookRFX.sql
  #   networks:
  #     - log_searchq_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=helloworld@domain.com
      - PGADMIN_DEFAULT_PASSWORD=helloworld
    ports:
      - '2345:80'
    networks:
      - log_searchq_network